/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.95
 * Generated at: 2024-06-20 17:35:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.app.dao.EmployeeDao;
import com.app.bean.Employee;
import java.util.*;

public final class editEmployee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/hp/Desktop/JavaEEWeb/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/JSPCRUD/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1716195662023L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.app.bean.Employee");
    _jspx_imports_classes.add("com.app.dao.EmployeeDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

  int id =Integer.parseInt(request.getParameter("id"));
 	out.print(id);
  Employee e=EmployeeDao.getEmployeeId(id);
  
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<h1>Edit Employee</h1>\r\n");
      out.write("<hr>\r\n");
      out.write("<form action=\"editEmp.jsp\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"id\" value=\"");
      out.print( e.getId() );
      out.write("\">\r\n");
      out.write("<table>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Name:</td>\r\n");
      out.write("<td><input type=\"text\" name=\"name\" value=\"");
      out.print( e.getName() );
      out.write("\"> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Password:</td>\r\n");
      out.write("<td><input type=\"password\" name=\"password\" value=\"");
      out.print( e.getPassword() );
      out.write("\"> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Email-Id:</td>\r\n");
      out.write("<td><input type=\"email\" name=\"email\" value=\"");
      out.print( e.getEmail() );
      out.write("\"> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Gender:</td>\r\n");
      out.write("<td>\r\n");

 if(e.getGender().equals("male"))
 {	

      out.write("\r\n");
      out.write("<input type=\"radio\" name=\"gender\" value=\"male\" CHECKED > Male\r\n");

 }
 else{

      out.write("\r\n");
      out.write("<input type=\"radio\" name=\"gender\" value=\"male\"> Male\r\n");

 }

      out.write("\r\n");
      out.write("\r\n");

 if(e.getGender().equals("female"))
 {	

      out.write("\r\n");
      out.write("<input type=\"radio\" name=\"gender\" value=\"female\" CHECKED > Female\r\n");

 }
 else{

      out.write("\r\n");
      out.write("<input type=\"radio\" name=\"gender\" value=\"female\"> Female\r\n");

 }

      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Country:</td>\r\n");
      out.write("<td>\r\n");
      out.write("<select name=\"country\" selected=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e.getCountry() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('>');
      out.write('\r');
      out.write('\n');

 if(e.getCountry().equals("India"))
 {

      out.write("\r\n");
      out.write("<option selected =\"selected\">India</option>\r\n");

 }else
 {

      out.write("\r\n");
      out.write("<option>India</option>\r\n");

 }

      out.write("\r\n");
      out.write("\r\n");

 if(e.getCountry().equals("Russia"))
 {

      out.write("\r\n");
      out.write("<option selected =\"selected\">Russia</option>\r\n");

 }else
 {

      out.write("\r\n");
      out.write("<option>Russia</option>\r\n");

 }

      out.write("\r\n");
      out.write("\r\n");

 if(e.getCountry().equals("USA"))
 {

      out.write("\r\n");
      out.write("<option selected =\"selected\">USA</option>\r\n");

 }else
 {

      out.write("\r\n");
      out.write("<option>USA</option>\r\n");

 }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<option>other</option>\r\n");
      out.write("</select>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td></td>\r\n");
      out.write("<td><input type=\"submit\" value=\"Edit\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
